name: run-as-non-admin
description: Run script without admin user privileges in windows runner

inputs:
  cmd:
    # with node 22, you must use the full path, e.g. c:\Program Files\nodejs\npm.cmd
    description: Command to run, e.g. npm
    required: true
  args:
    description: Arguments to pass to the command
    required: false
    default: ''

runs:
  using: composite

  steps:
    - name: Prepare env and run cmd as non-admin user
      shell: powershell
      env:
        OS: ${{ runner.os }}
        CMD: ${{ inputs.cmd }}
        ARGS: ${{ inputs.args }}
      run: |
        if ($env:OS -ne "Windows") { exit 1 }

        icacls $env:TEMP /grant "Everyone:(OI)(CI)F"

        $username = "notAnAdmin"

        $password = ConvertTo-SecureString "kragZTWET53$%" -AsPlainText -Force
        New-LocalUser $username -Password $password
        Add-LocalGroupMember -Group "Users" -Member $username
        $credential = New-Object System.Management.Automation.PSCredential ($username, $password)
        $process = Start-Process -FilePath $env:CMD -ArgumentList $env:ARGS -Credential $credential -PassThru -Wait -NoNewWindow -RedirectStandardOutput "output.txt" -RedirectStandardError "error.txt"
        Get-Content output.txt
        Get-Content error.txt

        if ($process.ExitCode -ne 0) { exit $process.ExitCode }
