# Usage

# - name: Step name
#   if: matrix.os == 'windows-latest'
#   uses: ./.github/actions/run-as-non-admin
#   with:
#     run: |
#       echo "whoami:$(whoami)"
#       npm run test:integration

name: run-as-non-admin
description: Run script without admin user privileges in windows runner

inputs:
  run:
    description: Multiline script to run, e.g. npm test
    required: true

runs:
  using: composite

  steps:
    - name: Prepare env and run cmd as non-admin user
      shell: pwsh
      env:
        OS: ${{ runner.os }}
        RUN: ${{ inputs.run }}
      run: |
        ./script.ps1
