name: run-as-non-admin
description: Run script without admin user privileges in windows runner

inputs:
  cmd:
    description: Command to run, e.g. npm
    required: true
  args:
    description: Arguments to pass to the command
    required: false
  user:
    description: User to run the command as
    required: false
    default: nonadmin

runs:
  using: 'composite'

  steps:
    - if: ${{ runner.os != 'windows' }}
      shell: pwsh
      run: |
        exit 1

    - name: Set env
      shell: pwsh
      env:
        CMD: ${{ inputs.cmd }}
        ARGS: ${{ inputs.args }}
        NO_ADMIN_USER: ${{ inputs.user }}
      run: |
        icacls $env:TEMP /grant "Everyone:(OI)(CI)F"

        $password = ConvertTo-SecureString "kragZTWET53$%" -AsPlainText -Force
        New-LocalUser $env:NO_ADMIN_USER -Password $password
        Add-LocalGroupMember -Group "Users" -Member $env:NO_ADMIN_USER
        $credential = New-Object System.Management.Automation.PSCredential ($env:NO_ADMIN_USER, $password)
        $process = Start-Process -FilePath $env:CMD -ArgumentList $env:ARGS -Credential $credential -PassThru -Wait -NoNewWindow -RedirectStandardOutput "output.txt" -RedirectStandardError "error.txt"
        Get-Content output.txt
        Get-Content error.txt

        if ($process.ExitCode -ne 0) { exit $process.ExitCode }
