name: run-as-non-admin
description: Run script without admin user privileges in windows runner

inputs:
  cmd:
    description: Command to run, e.g. npm
    required: true
  args:
    description: Arguments to pass to the command
    required: false

runs:
  using: 'composite'

  steps:
    - name: Set env
      shell: pwsh
      env:
        OS: ${{ runner.os }}
        CMD: ${{ inputs.cmd }}
        ARGS: ${{ inputs.args }}
      run: |
        if ($env:OS -ne "Windows") { exit 1 }
        $userName = -join ((65..90) + (97..122) | Get-Random -Count 10 | % {[char]$_})

        icacls $env:TEMP /grant "Everyone:(OI)(CI)F"

        $password = ConvertTo-SecureString "kragZTWET53$%" -AsPlainText -Force
        New-LocalUser $userName -Password $password
        Add-LocalGroupMember -Group "Users" -Member $userName
        $credential = New-Object System.Management.Automation.PSCredential ($userName, $password)
        $process = Start-Process -FilePath $env:CMD -ArgumentList $env:ARGS -Credential $credential -PassThru -Wait -NoNewWindow -RedirectStandardOutput "output.txt" -RedirectStandardError "error.txt"
        Get-Content output.txt
        Get-Content error.txt

        if ($process.ExitCode -ne 0) { exit $process.ExitCode }
