name: Enforce Changelog

permissions:
  contents: read

on:
  pull_request:
    types: [edited, opened, synchronize] # relevant triggers for title change, file modifications

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true


jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check changelog
        uses: cap-js/.github/.github/actions/check-changelog@main
