name: Linting

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cap-org-lint:
    uses: cap-js/.github/.github/workflows/lint.yml@main
    secrets: inherit
