name: Linting1

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint2:
    uses: cap-js/.github/.github/workflows/lint.yml@main
    secrets: inherit
