# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Release

on:
  push:
    branches: main

  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry run
        required: false
        default: false
        type: boolean
      tag:
        description: The tag to use during publish, values are latest, next
        required: false
        default: latest
        type: choice
        options:
          - latest
          - next

permissions:
  contents: write


jobs:
  release:
    uses: cap-js/.github/.github/workflows/release.yml@main
    secrets: inherit
    with:
      dry-run: ${{ github.event.inputs.dry-run || false }}
      tag: ${{ github.event.inputs.tag || 'latest'}}
